test: updated publish stage

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -278,6 +278,8 @@ jobs:
       - review_secrets
       - review-dog-misspell
     runs-on: ubuntu-latest
+    env:
+      NEEDS: ${{ toJson(needs) }}
     steps:
       - uses: actions/checkout@v2
         with:
@@ -301,8 +303,24 @@ jobs:
         with:
           name: Package
           path: dist/
+      - name: check if tests have passed or skipped
+        if: github.event_name != 'pull_request'
+        id: check
+        shell: bash
+        run: |
+          RUN_PUBLISH=`echo $NEEDS | jq ".[] |  select(  ( .result != \"skipped\" ) and .result != \"success\" ) | length == 0"`
+          if [[ $RUN_PUBLISH != *'false'* ]]
+          then
+              echo "::set-output name=run-publish::true"
+          else
+              echo "::set-output name=run-publish::false"
+          fi
+      - name: exit without publish
+        if: ${{ steps.check.outputs.run-publish == 'false' || github.event_name == 'pull_request'}}
+        run: |
+          echo " some test job failed. "
+          exit 1
       - name: Semantic Release
-        if: ${{ github.event_name != 'pull_request' }}
         uses: cycjimmy/semantic-release-action@v2.5.4
         with:
           semantic_version: 17
